In [10]:
!pip install lifelines

Requirement already satisfied: lifelines in /home/michalek/miniconda3/lib/python3.13/site-packages (0.30.3)
Requirement already satisfied: numpy>=1.14.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (2.3.3)
Requirement already satisfied: matplotlib>=3.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (3.10.8)
Requirement already satisfied: autograd>=1.5 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (1.8.0)
Requirement already satisfied: autograd-gamma>=0.3 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from lifelines) (1.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas<3.0,>=2.1->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas<3.0,>=2.1->lifelines) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas<3.0,>=2.1->lifelines) (2025.3)
Requirement already satisfied: interface-meta>=1.2.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines) (1.3.0)
Requirement already satisfied: narwhals>=1.17 in /home/michalek/miniconda3/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines) (2.15.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from formulaic>=0.2.2->lifelines) (2.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (25.0)
Requirement already satisfied: pillow>=8 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /home/michalek/miniconda3/lib/python3.13/site-packages (from matplotlib>=3.0->lifelines) (3.2.5)
Requirement already satisfied: six>=1.5 in /home/michalek/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=2.1->lifelines) (1.17.0)

In [11]:
# Libraries
import pandas as pd

In [12]:
# Import the dataset
dataset = pd.read_csv("data/lung.csv")
dataset.head()

,inst,time,status,age,sex,ph.ecog,ph.karno,pat.karno,meal.cal,wt.loss
0,3.0,306,2,74,1,1.0,90.0,100.0,1175.0,NaN
1,3.0,455,2,68,1,0.0,90.0,90.0,1225.0,15.0
2,3.0,1010,1,56,1,0.0,90.0,90.0,NaN,15.0
3,5.0,210,2,57,1,1.0,90.0,60.0,1150.0,11.0
4,1.0,883,2,60,1,0.0,100.0,90.0,NaN,0.0

In [13]:
# Data organization
dataset.loc[dataset.status == 1, "status"] = 0
dataset.loc[dataset.status == 2, "status"] = 1

In [14]:
# Get only variables needed
dataset = dataset.drop(columns = ["inst"])
dataset

     time  status  age  sex  ph.ecog  ph.karno  pat.karno  meal.cal  wt.loss
0     306       1   74    1      1.0      90.0      100.0    1175.0      NaN
1     455       1   68    1      0.0      90.0       90.0    1225.0     15.0
2    1010       0   56    1      0.0      90.0       90.0       NaN     15.0
3     210       1   57    1      1.0      90.0       60.0    1150.0     11.0
4     883       1   60    1      0.0     100.0       90.0       NaN      0.0
..    ...     ...  ...  ...      ...       ...        ...       ...      ...
223   188       0   77    1      1.0      80.0       60.0       NaN      3.0
224   191       0   39    1      0.0      90.0       90.0    2350.0     -5.0
225   105       0   75    2      2.0      60.0       70.0    1025.0      5.0
226   174       0   66    1      1.0      90.0      100.0    1075.0      1.0
227   177       0   58    2      1.0      80.0       90.0    1060.0      0.0

[228 rows x 9 columns]

In [15]:
# Cox Proportional hazard
from lifelines import CoxPHFitter
model = CoxPHFitter()
model.fit(dataset, "time", event_col = "status")
model.print_summary()

TypeError: NaNs were detected in the dataset. Try using pd.isnull to find the problematic values.

In [ ]:
# Plotting
model.plot()