In [1]:
!pip install spacy --upgrade

Requirement already satisfied: spacy in /home/michalek/miniconda3/lib/python3.13/site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/michalek/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/michalek/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: cloudpickle>=2.2.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from srsly<3.0.0,>=2.4.3->spacy) (3.1.2)
Requirement already satisfied: ujson>=1.35 in /home/michalek/miniconda3/lib/python3.13/site-packages (from srsly<3.0.0,>=2.4.3->spacy) (5.11.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in /home/michalek/miniconda3/lib/python3.13/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/michalek/miniconda3/lib/python3.13/site-packages (from jinja2->spacy) (3.0.2)

In [2]:
!python -m spacy download en_core_web_sm

/home/michalek/miniconda3/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.1) or chardet (7.0.1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 8.0 MB/s  0:00:01a 0:00:01m eta 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [3]:
import spacy
import en_core_web_sm
import pandas as pd
import seaborn as sns
import numpy as np
import re
import random

/home/michalek/miniconda3/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.1) or chardet (7.0.1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [4]:
train_data = pd.read_csv('data/train.csv', header = None,
                         names = ['sentiment', 'id', 'date', 'query', 'user', 'text'], encoding='latin1')

In [5]:
train_data

,sentiment,id,date,query,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [6]:
train_data['sentiment'].unique()

array([0, 4])

In [7]:
# sns.countplot(train_data['sentiment']);

In [8]:
np.unique(train_data['sentiment'], return_counts=True)

(array([0, 4]), array([800000, 800000]))

In [9]:
train_data = train_data.drop(['id', 'date', 'query', 'user'], axis=1)
train_data

         sentiment                                               text
0                0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1                0  is upset that he can't update his Facebook by ...
2                0  @Kenichan I dived many times for the ball. Man...
3                0    my whole body feels itchy and like its on fire
4                0  @nationwideclass no, it's not behaving at all....
...            ...                                                ...
1599995          4  Just woke up. Having no school is the best fee...
1599996          4  TheWDB.com - Very cool to hear old Walt interv...
1599997          4  Are you ready for your MoJo Makeover? Ask me f...
1599998          4  Happy 38th Birthday to my boo of alll time!!! ...
1599999          4  happy #charitytuesday @theNSPCC @SparksCharity...

[1600000 rows x 2 columns]

## Train and test data

In [10]:
X = train_data.iloc[:, 1].values
X

array(["@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D",
       "is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!",
       '@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds',
       ..., 'Are you ready for your MoJo Makeover? Ask me for details ',
       'Happy 38th Birthday to my boo of alll time!!! Tupac Amaru Shakur ',
       'happy #charitytuesday @theNSPCC @SparksCharity @SpeakingUpH4H '],
      dtype=object)

In [12]:
y = train_data.iloc[:, 0].values
y

array([0, 0, 0, ..., 4, 4, 4])

In [13]:
from sklearn.model_selection import train_test_split
X, _, y, _ = train_test_split(X, y, test_size = 0.97)

In [14]:
X

array(['@Niki7a a very good idea ',
       'Wings r one away from the stanley cup!!  ',
       '@saultheturtle, thank you! ', ...,
       'Good morning! (to some good nite) I hope you had an enjoyable weekend ',
       '@SandyFowler Thank you for the very kind words about my latest blog post/story! Glad you enjoyed it! Sending smiles ... ',
       "I hate how Victoria Beckham spells 'colors' like 'colours' &amp; 'favors' like 'favours' "],
      dtype=object)

In [15]:
X.shape

(48000,)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [17]:
X_train.shape, y_train.shape

((38400,), (38400,))

In [18]:
X_test.shape, y_test.shape

((9600,), (9600,))

In [19]:
np.unique(y_train, return_counts=True)

(array([0, 4]), array([19326, 19074]))

In [20]:
np.unique(y_test, return_counts=True)

(array([0, 4]), array([4759, 4841]))

# Preprocessing the data

In [21]:
nlp = spacy.load('en_core_web_sm')
nlp

In [23]:
def preprocessing(sentence):
  sentence = sentence.lower()
  sentence = re.sub(r"@[A-Za-z0-9]+", ' ', sentence)
  sentence = re.sub(r"https?://[A-Za-z0-9./]+", ' ', sentence)
  sentence = sentence.replace('.', '')
  tokens = []
  tokens = [token.text for token in nlp(sentence) if not (token.is_stop or token.like_num or token.is_punct or token.is_space or len(token) == 1)]
  tokens = ' '.join([element for element in tokens])

  return tokens

In [24]:
preprocessing("@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  2 You shoulda got David Carr of Third Day to do it. ;D")

'awww bummer shoulda got david carr day'

In [25]:
X_train_cleaned = [preprocessing(tweet) for tweet in X_train]

In [26]:
len(X_train_cleaned)

38400

In [27]:
for _ in range(10):
  print(X_train_cleaned[random.randint(0, len(X_train_cleaned) - 1)])

hi peter think awesome play carlisle way imagined rock
yay bj lorraine amd baby hahaha
wow day talk blame nice luv
going town today cos lazy yesterday lol gona breakfast
damn youuuuuuu want subway
yes like blipping tunes
left amp union sqi miss em
fail cheer freedoms land watch taken away
congrats bnet cnet aop ftws slightly jealous watch backs lads ladettes
cahhh transferring chino hills bit

In [28]:
X_test_cleaned = [preprocessing(tweet) for tweet in X_test]

## Word cloud

In [29]:
texts = ''
for text in X_train_cleaned:
  texts += ' ' + text

In [30]:
texts

" coffee time tried sending picture morning stayed quot;sending twitpic quot screen forever wrong nita phone stopped allowing send texts keeps failing resting long tough day beautiful wife disapointed jon amp kate trouble internet police sexual harrassment twitter fuckkkk classic course chris speak truth think disappeared answered got iphone touch hello found guys wefollow 5:30am coffee having apple instead 3turnoffwords lets friends time steve found geocache kl bit sweating sure heat walk ummmm probably known oldies lol truly love types left restraunt table air force guys uniform yay watching ass stuck road poorly francis having sleep nite amp hay fever raping real thoit looks like girl threw large shirt pinned legs called dress saying goodbye hubby called giddy hottie calls darn got shortlisted floor job guess coverletter good interview quot;get like storm keeps heading way everyday shelter&quot blue_wolf spare iphones van sorry try glad spread word got 2:2 happy happy amp amazing people life right good luck girlies fab time finally bed sure feel amazing lay cry inside awesome bands failed listen congrats getting typography displayed gallery totally love lt;3 yummy dinner gross took forever tasted like dog food probably nice hate food  body aching nt thought aftermath chalet bad ehhh xbox nt update twitter facebook think looks good years enjoyed sunshine today apparently tsunami heading way hours home ill wanna work today hoping little kid craps pool shut thanks oocss recogn loose objects wonder cascade feature bug approach cascade css happy cool weather having maine oh new wondeing casatiello dense happily enjoying theirs liquor store fail canadian mythos ftw is_king intro sam amp max hit road youtube lmao lost car keys yesterday ha yeah know nice thought aaah think dying haha needin nicholas jerry jonas celsius today enjoy sooooo waisting summer break sorry today damnit'sworktomorrowday yaaay youuuuu going home chillen tired working peace â\x99¥ want excuse buy clothes lol know sell copies sure lol way day consecrainy days nj xo okay recording arrived gym think chocolate cake damnit bad katherine morning shining sun hey hun pretty good study gon na try close finals wait music album released want nowwww hoping cousin stand today knocked door wanted kfc guess sleeping lol eating breakfast wish saw nadal vs djokovic matchwould've awesome pleasure watching nadal play sheets washednow bed finished exams week got loads term melbourne airport live flight radar cool little plane uk making way wa blog sad says connected google connect hih good morning austria 17:36 hihi sad thing fatfriday lunch ended eating toasts chesse 4:00 goodnight dude discussing thing think tethering work phones hates wishes meet mr robert pattinson ahh like lovely man yea let look like game fan pre ordering things day ages unbelievably bored everyones busy oh taste london good tomorrow listening ryan adams death cab goood evening having trs waiting missed loved people derrin true makes smile thanks sunny day wasted finally inbox newsletters read open tabs browser bookmarked tagged loving fiji right thanks homeskilletbiscuit warped tour going muah ha ha ha hope title race maybe man city favor eat today amp hope xabi alright hey great meet site find course welcome live summer house fine hedgehogs conservation area maybe nt slice cake feel major sick blah wish save hours away gee sorry sure time work video hereï¿½s wishing bluest skies wait death london tomorrow saturday night feeling canceled fete de la musique drinks friend bar sobs thanks phillip truly amazing day experience 50miles spent week sea waiting aquatic skills want sleep lot tomorrow nt wake o'clock single day uu que ladilla email emileevitrano com emilee vitrano dream dad wo nt change lol kurtis house life know far obsessive love crisply bed sleep  okay period totally screamed dog think lost summer job morning dnt 4get mtv movie awards 2night sort smiley tweet guess obsession smileys like describing feel lt;3&lt;3&lt;3 wha hurt feelings chee miss need important oliver yummy attempting chocolate fudge cake books tonight great friends helping enrollment feel lucky g_x yeah read rumours gon na suprises know haha xx bom dia twitters noticed find good reruns cancelled cleaning bullshit gorefest split hmm chocolate cake xd gon na pig tonight pigging night food thank karen burning midnight oil thankful church 1:00 service love summer school sadly teachers hot went floor building bc hydro open house thingamabobber love office cozier floor hatch glad introduced cpain ps know tonight son quincy short awww sserd miss place need catch money saving tips amp washing hey fellow muslim holden amazing goodmorning goodmorning 2day gloomy day ugh weather blows yo nt qet strike lmao details project team interested grade typing class told cheating egads late sleepless mon night road headed north mommy yes mommy girl beauty love light amp peace birthday present thanks everyonefor time sleep work crazy saturday break omg fires santa barbara?sorry live canada heard oh gosh horrible haha thanks new site looking good need hand let know went date truly single sucks audit today gah cause old ehehehe chews broken headphone pathetically going live new ones fit avenue kids hi herefinally yay seriously day oh fellow hell ruler  working mins home hello wonderful followers follow request site hope lawrence yep want dinner loom room tonight ham god nice guy love walk meters hugs thanks funny got ta optimistic came argentina dream come true nt c28 oops missed replies lol thanks great day force eyes stay open going bed write amp tweet later love friday saturday sunday monday hes way vegas looking fierce amp bronzed bakersfield lcat aw nt believe everyones gone home summer grove till degree miss keke piss hopefully company create legit eventually 2hour maths exam ohhh sorry honestly kevin odd fucking pissed love kevin truly favorite know look magazines future frustrated afraid sad lethargic kind life worked till work roofing tired helping family roof old good hungry locked office update posted umm todaaaay got home 10minutes ago felt sick day work good lool ok turned hubby unsalty loving person gt tweet accident amazing gave downloading right listened faromj incredible finance management pre reading includes pages got xbox josh updating b4 work thinks follow friday thing fun dollars bank account right got ta save gas thursday think heard going rain sunday gtalk plus orkut works hate gtalk service friends use gtalk switch windows live skype whoa think lol sorry awww thx gifts sure owe sumthing kidding long hungry eat pshhh girl feel like crying big sing sorry hope voice comes wooof photoshoot audition good luck orientation night dead boring right sad helps stop bothering education arrives daughter social event high school quot;big sister&quot conflict management training today thanks felipe laurs leaving days tt_tt play lol having stressful morning got computer crashed trying reinstall oh wow actually realxing eh waste time haha awesome great hear victoria nite lovey like spring snow local place buy free canceled bad lost business great having website finding traffic major pain working ideas great day rockets won crawfish spicy margaritas bomb recovering night gon na drink excited m&amp;m finally missed liking spoilers week oh boy love weekends peer pressure peer pressure need carbs offered cheque substitute like said send cleared afford taking submissions chance video hope realize website blocked china live wuhan proxy site grandparents house crampsss suckkk monkeyyyy ballssss byeee miss yaahh tweet ure remembered coast friend birthday friday night morning tweeters today weather terrible believe 15c degrees hotter days ago coz busy driving mysore trichur btw kind theatre pounds crazy increase lot evidently good favorite words moles got moles voles mice chippies squirrels everybody needs teddy good luck today laaaavly jessicab_xx audiance like hi jess lmao yeah feeling good omg casey flippin baby girl emory aline perfect future sweet briar girl class power cut watching telugu movie anand maatv fans peru remember food great haha trying tv work went ended staying surprise bday party sure mad work fantastic coup totally pick comes love anthologies shout areas page heavily frequented bysouth bend indiana amp grand rapids michigan bout head emergency room xd shit caffeine hyped xd doc sezs need lay happen lot sg know oh think want desert new mexico starved death baby bump showing lot got quot;is baby&quot question based belly prior convo says reviewingbut feeling oooooh saw moose road kill sooo big best weekend caty costigans house marley fest promcomes crashing paper tomorrow 10:25am lazy xxxxx rip farrah fawcett sorry hear news mm yep rin knw hurts bad hahaha thanks yeahhh shud want workthe good thing need wear suit jeans day everyday yeasee order nt eat box home stuff chiken wings truck went legs enjoyed dancing yesterday best celebration years ï¿½// soooo houston building twitter planning week happy friday gettin ready work wondering today shame weather longest day whoo wheee miss sister nieces best mood guess gon na use twitter bashing ppl sorry read mean things ya heads boys girls willing share banana blueberry mini loaves bakes morning wanna london looooooooool sucks living kent haha music time omg long day work train rain rain away business day month wrong time new tags people ughh tired need shower oh morning movie awesome lis ð¿ð¸ñ\x82ñ\x8c ð½ð ð´ð ð¼ðµð½ñ\x8cñ\x88ðµ long day tired feelin mccoy peanut chicken stir fry pre scratch pleased turned good hahaha yah felt like total creeper like friends ill nevere beat good times think saw respond people awhile ago let know said hi think fair husband having nice inpromptu sp pub lunch family stuck work great pics loaded sexy classy nice lol haha funny hamper realize til got halfway baytown jp later tonight ghost hunting thing fucking scary dinner carrot cake good rubbed eye sore aw pissed like mike missed love bow wow friends mail cards let ones covered dicks vag goodnight angel fantastic week dying hur working milano breeze natural creative time visiting website time bothered today talk servers crashing like halfway follow chair backing fan hands instead watcing llâ´â look magazine gon na wake tomorrow gon na job hunting sweeties studying sucks wanna nap dj dj fruit loops diabetic love eat simply nt okso heading ct o'clock flightwill miss girls mary precious development hardware precisely going going write blog post realized post advice feedback day improve time estimation argh!\\ uhhh hate sick especially graduation come hiya felicia yes new account ok dude glad home pretty sure feline hitchhinkers pretty good thanks struggling lame website design bit getting sick marty lol girls murdered week mind team gettin readyy workkk shoot meeee allergys bad nose bleeding days straight sad face meh probly jason ellis pete likes big boys tiredd working 8:30 7:30 th effectiveness flu shot flu like symptoms persist sold yorkshire terrier puppy litteri miss oh idea unplugged cable xmastime dvd sorry surprisingly twitter reduce boredom bored thanks followfriday props heck yeah excited thank stupid crap need time day gone brain dead time pack head home day day productive pics myspace acute sinusitis wish bed right dad totally rocked offspring pretty fly white guy haha google wave demo video 1:20:11 short attention span holy crap love tasty cakes try butterscotch frosted ones told bff -i nt vegas wedding bummerz feel bad ciao care miss ah sex car wash good day everyonr peace ottawa dads overseas fathers day understudy ladies yea totally agree miss watching cartoon version like newer version makes lol ahh good idea thank gt;u&lt followfridaying aww sorry handle business let clelbrate :p entourage party think way road hell amp think obama saw sony pulled chris paladino qore video w/ psp e3 watching woman reality tv obese stopped fast food meals hungry feel sad wish princess protection program premiere tonight got ride probably wo close seeing tummy smiles miss mission hills home omg look differentomg hell going wait exams insha'allah days time shall free head going work day belly piercing soo soreee promotions 2marrow quot;pretty committee&quot srry know wat dem fun having dress hoping great weeks yes yes yes peacocks dream tour moment guys happen bit concerned wolves flag fly away awww video today going shoes lol needed fix man save money dish detergent order right oops bad influence meant twitter thumb failed eating dinner outside tripping balls cause baby replying soooo paranoid got overdue bath today hind legs hair sticking humidity making hair straight   great rehearsal outside playing neoghbors dog alternate motrin tylenol hours fever pops hope gets better soon arghhh hate airports excellent runoff gym pt little light martial arts went cousins softball game won yeahh bitch like gut feeling right bad arg smile hardly looked good face video shuld concentrate interviewee going movie hangover pm peter mandelson way rhny lost episodes awesome excited feeling good going yeah saw free concert festival da juventude danced lot virgiq toco!!!doeu video believe sure watch live europe hope start feeling soon m'friend got home long vacant time day hours swear bored time explain oh feel pain ur tweet sad sorry follow interesting people share good content engage conversations pretty kiss sweetheart look properties week theirs suitable nt dogs punk look lacy talking sara jeremyyy send text going cell phone lot listening radio disney waiting parents soon questions ridicule begin thinking job currently giving stress deal angry people like bit vixen date avaliable people choose thirsty weeks end till thn whr matches tak place?no matches chennai match year nt watch damn video wish coming waters fully intend getting hangover got zoom lens hell yeah oh good following updates want free bmw gnight ms trina soooo glad know bball fan awesome rock diamond princess hoy es sabado going loop later apply jobsss happy birthday dad love making house phones broke miss beauty hawaii need vacation use irfanview batch resizing think watermark feature yes ma'am right god gave rock roll bill ted wanna technical andyhurleyday ty gurl eating cherries watching world history idol bed colby tomorrow iphone broke work old phone goes hopper haha true boring douchebags days holidays left homework lol great surprises lola kanina quot;&gt cookies things soo funnier feel sleepy words gigglesome join haha right bout lunch wit da fam b4 aunt catches flight hey ok setting watching rain bleh nice outside finish bit work great day brighton gone eat taping hills episode reading notes people wrote yearbook misspelled times 1:00pm came home early school today sore throat fatigue fever soon thanks stress work yay happy fridays off3 day weekends summer true think knows uhhhg siiicck ouuchh mega prayer night soooo goood amazingamazing possible god trust him!!incredible night wants skate rainy awake hours clock check capesnbabescom reading union heroes switching forth german english day come ranchi away net listening camp rock songs mood loving voice ordered join twitting bandwagon follower pllllllllllllllllllllllllllz come wash car today sad got home party night falls hour ago party mode yay true write seeing ipl hopefully weather clears going dinner like mommy paid preparing kids mid term exam problems easy job mom dayswaiting head explode soon point turning eat read socrates thoughts long time bed science studying tomorrow tear oh terrible xxx thx girlie enjoying found app trial purchase app head happen people mad reason neck shoulder strain today lot pain wonders going signs todayyy absoutley love taylor launter hook upp rip cris isaac amp;sethen hold strong little turn soon believe days thankful successful communionand looking forward birthday soon hey meera like strips smart hey good lol u?x omg saw trailer wanna photos come closer nice feel free chip anytime new zune hd coming oldbut alas spent quota year wait coffee bad link drudge report article nowthanxx buttercup airport getting ready head la awww home florida come goodbye degrees hello credit score higher population star gold charlottenthon stã¸ttes anoooo dare interfere ma twittering schedule ahaha home sadly  wanna tomorrow hopefully angie magically comes gets hint rawr ugh hay fever bad today clinging trying figure husband twittering class proves add got ta love lt;&gt;&lt quot;success pursued attracted person become&quot luv quote ur fav quote dad star trek smells like humidor inside took hope better reallllly good morning hay honey sip tea b4 tackle world 2day havin stand da train suppose keepin awake legs killin welcome friends listyour twitter sounds like super hero end aug!x yes blog sucks knowing awesome logo sketched time finesse idea illustrator deadline hilarious dream night wish fun day went fig geena aftere long weekend working making tips seaside internet download facecage cambridge tomorrow huuurt voice good morning cool join chuckers timezone issues chuckmemondays min liked cudnt help cracking joke eye candy lolzzz said na nice dp prev tweet heartburn vodka irn bru  hurt hand awww manim sorry hear want spring warm time instead decastro yess decemberhaaay hit got wait airport wanna come home happy birthday found purse notebook yay stop cleaning paris yes likes song quot;pass on&quot knife oh word time need pee need vote district let vote district let vote know bby mas thankshelped justate happy birthday @_marney guess got ta nswer queenslander important rest  welcome twitter mom dazzled beauty listening blues writing school paper3 papers days end programcan tell wait tons love going way twitter quiet tonight meeting strangers lol vegas amazing good morning twitter darlings sun brief cameo morning hyped ran hiding time breakfast keeps asking getting blink-182 tickets wednesday yep hoping fix relationship kids guess hey friend reason record stores cause supports local business itunes zune mp3 places cool saw 3d amazazing loved miss babe disappointed decisions tea week looking forward bring weather dundee meant normal scottish summer time cold wet team freeze stoopid grand prix offered chance meet script tomorrow night silverstone love best friend amazing way thanks girl lt;3 ottawa deprived lol live auckland new zealand visited nz follow wo lead wrong lmao come visit miss cokers wait july anymore lol like minutes lol makes sense enjoy appreciate followfriday noooo bird bites dust garden courtesy cat need un follow people talking celebritys becuase ipod dead evrmorning cus talk yvonne till a|am happy saturday hot stuff sorry desk area messy promise better cubicle mate miss touch heart sweetest revenge lol stop bikini talk beautiful thing dec year2100 cheers mate mancs stick hahahaha listening u2 ~7d40q follow makes smile twitpic going need card love pink especially aussie family uh ohbad news dc md metro train crash dead connect twitter facebookhmm gooood duh work haha omg twitter awesome quot;when done&quot lacour yeh know hope great amp remembeeeer usa great bac great xd chatter box today sorry learning use twitter gosh hate guys damn perfect ughhh homeless sad homeless waiting golden bus leamington warwick minutes late lol yep hard pace cheers great day eating chips dip lunch breakwish bomb ass johhny pastrami hot dog shit lol think obsessed tumblr cool xix gaat juni weer eens fun working til tonight watching spongebob weird saying goodnight separate end era hello cream section year mic told got transferred new section wish mom look guide life horrible despressed frustrated ugly type mom rent cried like fukn baby today durin da senior showima miss senior friends way workneed tanim looking sooo verry extra liteskin days disappointed got cardigan dress amp backpack boyf today updated monsterattackslj tonight cool hope nt rain fuuuuuuuuuuuuuuuuuudge hungry finally bed h