In [4]:
!pip install chaid
!pip install graphviz

Requirement already satisfied: chaid in /home/michalek/miniconda3/lib/python3.13/site-packages (5.4.3)
Requirement already satisfied: cython in /home/michalek/miniconda3/lib/python3.13/site-packages (from chaid) (3.2.4)
Requirement already satisfied: numpy in /home/michalek/miniconda3/lib/python3.13/site-packages (from chaid) (2.1.3)
Requirement already satisfied: pandas in /home/michalek/miniconda3/lib/python3.13/site-packages (from chaid) (2.3.3)
Requirement already satisfied: treelib in /home/michalek/miniconda3/lib/python3.13/site-packages (from chaid) (1.8.0)
Requirement already satisfied: scipy in /home/michalek/miniconda3/lib/python3.13/site-packages (from chaid) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas->chaid) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas->chaid) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/michalek/miniconda3/lib/python3.13/site-packages (from pandas->chaid) (2025.3)
Requirement already satisfied: six>=1.5 in /home/michalek/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->chaid) (1.17.0)
Requirement already satisfied: graphviz in /home/michalek/miniconda3/lib/python3.13/site-packages (0.21)

In [5]:
# Import libraries
import pandas as pd
import statsmodels.api as sm
from CHAID import Tree

In [7]:
# Import data
data = sm.datasets.get_rdataset("ResumeNames",
                                package = "AER").data
data.head()

,name,gender,ethnicity,quality,call,city,jobs,experience,honors,volunteer,...,minimum,equal,wanted,requirements,reqexp,reqcomm,reqeduc,reqcomp,reqorg,industry
0,Allison,female,cauc,low,no,chicago,2,6,no,no,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
1,Kristen,female,cauc,high,no,chicago,3,6,no,yes,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
2,Lakisha,female,afam,low,no,chicago,1,6,no,no,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
3,Latonya,female,afam,high,no,chicago,4,6,no,yes,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
4,Carrie,female,cauc,high,no,chicago,3,22,no,no,...,some,yes,secretary,yes,yes,no,no,yes,yes,health/education/social services

In [8]:
# Remove name variable
data = data.iloc[:,1:]
data.head()

,gender,ethnicity,quality,call,city,jobs,experience,honors,volunteer,military,...,minimum,equal,wanted,requirements,reqexp,reqcomm,reqeduc,reqcomp,reqorg,industry
0,female,cauc,low,no,chicago,2,6,no,no,no,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
1,female,cauc,high,no,chicago,3,6,no,yes,yes,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
2,female,afam,low,no,chicago,1,6,no,no,no,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
3,female,afam,high,no,chicago,4,6,no,yes,no,...,5,yes,supervisor,yes,yes,no,no,yes,no,manufacturing
4,female,cauc,high,no,chicago,3,22,no,no,no,...,some,yes,secretary,yes,yes,no,no,yes,yes,health/education/social services

In [9]:
# Find unique values
data.apply(pd.Series.nunique)

gender           2
ethnicity        2
quality          2
call             2
city             2
jobs             7
experience      26
honors           2
volunteer        2
military         2
holes            2
school           2
email            2
computer         2
special          2
college          2
minimum         13
equal            2
wanted           6
requirements     2
reqexp           2
reqcomm          2
reqeduc          2
reqcomp          2
reqorg           2
industry         7
dtype: int64